### ISSUE TITLE
Doesn't build with latest Cython 

### ISSUE THREAD

**Issue by wolfv** [symengine/symengine.py#66]
I tested Cython==0.24 (the latest from pip) and it did not build with the following traceback.

It did work with Cython==0.22 though.

```
Error compiling Cython file:
------------------------------------------------------------
...
    cdef double complex[::1] cmplx_view
    if real:
        try:
            real_view = iterable
        except (ValueError, TypeError):
            real_view = cython.view.array(shape=(_size(iterable),),
                                                     ^
------------------------------------------------------------

symengine_wrapper.pyx:2464:54: Compiler crash in TransformBuiltinMethods

ModuleNode.body = StatListNode(symengine_wrapper.pyx:1:0)
StatListNode.stats[161] = StatListNode(symengine_wrapper.pyx:2455:0)
StatListNode.stats[0] = DefNode(symengine_wrapper.pyx:2455:0,
    doc = u' if iterable supports the buffer interface: return iterable,\n        if not, return a cython.view.array object (which does) ',
    modifiers = [...]/0,
    name = u'with_buffer',
    num_required_args = 1,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0')
DefNode.body = StatListNode(symengine_wrapper.pyx:2456:4)
StatListNode.stats[0] = IfStatNode(symengine_wrapper.pyx:2460:4)
IfStatNode.if_clauses[0] = IfClauseNode(symengine_wrapper.pyx:2460:7)
IfClauseNode.body = StatListNode(symengine_wrapper.pyx:2461:8)
StatListNode.stats[0] = TryExceptStatNode(symengine_wrapper.pyx:2461:8)
TryExceptStatNode.except_clauses[0] = ExceptClauseNode(symengine_wrapper.pyx:2463:8)
ExceptClauseNode.body = StatListNode(symengine_wrapper.pyx:2464:12,
    is_terminator = True)
StatListNode.stats[0] = SingleAssignmentNode(symengine_wrapper.pyx:2464:41)
SingleAssignmentNode.rhs = GeneralCallNode(symengine_wrapper.pyx:2464:41,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 8035, in compile_time_value: DictNode(symengine_wrapper.pyx:2464:47,
    is_dict_literal = True,
    is_temp = 1,
    obj_conversion_errors = [...]/0,
    reject_duplicates = True,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 7334, in compile_time_value: TupleNode(symengine_wrapper.pyx:2464:49,
    is_sequence_constructor = 1,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 6730, in compile_time_value_list: TupleNode(symengine_wrapper.pyx:2464:49,
    is_sequence_constructor = 1,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 4981, in compile_time_value: SimpleCallNode(symengine_wrapper.pyx:2464:54,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 1783, in compile_time_value: NameNode(symengine_wrapper.pyx:2464:54,
    cf_maybe_null = True,
    is_name = True,
    name = u'_size',
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/ExprNodes.py", line 1781, in compile_time_value
    return denv.lookup(self.name)
AttributeError: 'NoneType' object has no attribute 'lookup'
```

**Comment by isuruf** [comment]
This is a bug introduced in Cython 0.24 and reported here, https://mail.python.org/pipermail/cython-devel/2016-April/004771.html

**Comment by wolfv** [comment]
I see. 

Would be nice if it was mentioned in the README! 

Best,

Wolf

**Comment by certik** [comment]
@wolfv yes, we should mention this. Usually the libraries that we depend on are backwards compatible, but this was unfortunately a bug that got released.

Perhaps there is some kind of a workaround that we could use, so that it works with Cython 0.24.

**Comment by wolfv** [comment]
I am, unfortunately, not an CPython expert so I don't know any workaround. 

I quickly tested casting the size argument or using `cdef int` because I was under the impression the compiler thinks it could be a None value, but it didn't work out :)

**Comment by isuruf** [comment]
This issue is easy to fix by changing the named arguments into regular arguments. After it is fixed a whole lot of other errors are revealed.

```
  SymEngine::Basic const __pyx_t_1;

/* "symengine/lib/symengine_wrapper.pyx":380
 * 
 *     def __hash__(self):
 *         return deref(self.thisptr).hash()             # <<<<<<<<<<<<<<
 * 
 *     def __dealloc__(self):
 */
  try {
    __pyx_t_1 = * __pyx_v_self->thisptr;
  } catch(...) {
    __Pyx_CppExn2PyErr();
    __PYX_ERR(0, 380, __pyx_L1_error)
  }
```
See the above generated method. Here deref argument is stored and the argument type is wrong. `  SymEngine::Basic const`. It should be a const reference to a `SymEngine::Basic`.

**Comment by certik** [comment]
Does it look like Cython is completely broken?

**Comment by isuruf** [comment]
@certik, yes looks that way

**Comment by rwst** [comment]
Same with Cython-0.24.1.
